import Head from 'next/head';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.css';
import Login from './../components/Login';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Date generator</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

   <Layout>
    <h2>Don t ever run out of ideas</h2>
    <Login />
   </Layout>

    </div>
  );
}
